import pg from 'pg';
import 'dotenv/config';
import pkg from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const { PrismaClient } = pkg;
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
    console.log('🌱 Resetando tabelas...');

    await prisma.participantes.deleteMany();
    await prisma.personagem.deleteMany();
    await prisma.livro.deleteMany();
    await prisma.videoAula.deleteMany();
    await prisma.curiosidade.deleteMany();
    await prisma.dicas.deleteMany();
    await prisma.simulado.deleteMany();

    console.log('📦 Inserindo dados...');

    // Usuario
    await prisma.participantes.createMany({
        data: [
            {
                nome: 'Arthur Morais',
                curso: 'Desenvolvimento de Sistemas',
                curse: 'Systems Development',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'arthur.m.santos20@aluno.senai.br',
            },
            {
                nome: 'Pedro Arthur',
                curso: 'Eletroeletrônica',
                curse: 'Electronics',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'pedro.vitorino7@senaisp.edu.br',
            },
            {
                nome: 'João Victor',
                curso: 'Desenvolvimento de Sistemas',
                curse: 'Systems Development',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'joao.v.gomes50@aluno.senai.br',
            },
            {
                nome: 'Davi Camoleis',
                curso: 'Eletroeletrônica',
                curse: 'Electronics',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'davi.c.nascimento8@aluno.senai.br',
            },
            {
                nome: 'Felipe Augusto',
                curso: 'Fabricação Mecânica',
                curse: 'Mechanical Manufacturing',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'felipe.tonhatti@portalsesisp.org.br',
            },
            {
                nome: 'Rafael Santos',
                curso: 'Desenvolvimento de Sistemas',
                curse: 'Systems Development',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'rafael.s.mendes6@aluno.senai.br',
            },
            {
                nome: 'Davi Nobrega',
                curso: 'Eletroeletrônica',
                curse: 'Electronics',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'davi.nobrega3@portalsesisp.org.br',
            },
            {
                nome: 'Yasmim Vitória',
                curso: 'Eletroeletrônica',
                curse: 'Eletronics',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'yasmim.santos56@portalsesisp.org.br',
            },
            {
                nome: 'Gustavo Teixeira Lisboa',
                curso: 'Desenvolvimento de Sistemas',
                curse: 'Systems Development',
                foto: '[vamos tirar a foto depois]',
                idade: '16 anos',
                age: '16 years old',
                email: 'gustavo.t.lisboa@aluno.senai.br',
            },
            {
                nome: 'Victor Ferreira de Oliveira',
                curso: 'Desenvolvimento de Sistemas',
                curse: 'Systems Development',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'victor.f.oliveira14@aluno.senai.br',
            },
            {
                nome: 'Antonio Gabriel',
                curso: 'Eletroeletrônica',
                curse: 'Electronics',
                foto: '[vamos tirar a foto depois]',
                idade: '17 anos',
                age: '17 years old',
                email: 'antonio-silva38@portalsesisp.org.br',
            },
            {
                nome: 'Pedro de Siqueira Silva ',
                curso: 'Eletroeletrônica',
                curse: 'Electronics',
                foto: '[vamos tirar a foto depois]',
                idade: '16 anos',
                age: '16 years old',
                email: 'pedro.silva34@portalsesisp.org.br',
            },
        ],
    });

    await prisma.personagem.deleteMany();

    // Livro com personagens
    await prisma.livro.create({
        data: {
            titulo: 'Os Ratos',
            capa: 'https://i.ibb.co/kgkfQfXh/the-rats.jpg',
            autor: 'Dyonélio Machado',
            anoPublicacao: 1935,

            detalhesAutor:
                'Dyonélio Tubino Machado (1895–1985) nasceu em Quaraí, no Rio Grande do Sul. Médico psiquiatra, jornalista e escritor, é um dos nomes centrais do Modernismo de 1930. Sua formação em psiquiatria marca profundamente sua ficção: ele constrói personagens a partir de gestos miúdos, impulsos e pensamentos quase imperceptíveis, revelando a psicologia do homem comum submetido à pressão social e econômica. Foi preso por questões políticas, filiou-se ao Partido Comunista e chegou a dividir uma cela com Graciliano Ramos. Ao longo da vida publicou 19 títulos, mas é com Os Ratos que seu nome permanece na literatura brasileira.',
            detalhesAutor_en:
                'Dyonélio Tubino Machado (1895–1985) was born in Quaraí, Rio Grande do Sul. A psychiatrist, journalist, and writer, he is one of the central figures of Brazilian 1930s Modernism. His medical background deeply shapes his fiction: characters are built through small gestures, impulses, and near-imperceptible thoughts that expose the psychology of ordinary people under social and economic pressure. He was imprisoned for political reasons, joined the Communist Party, and shared a cell with fellow writer Graciliano Ramos. Over his lifetime he published 19 titles, but it is The Rats that secured his place in Brazilian literature.',

            genero: 'Romance psicológico, Realismo social, Modernismo de 1930',
            genero_en: 'Psychological novel, Social realism, 1930s Brazilian Modernism',

            resumo: 'O livro acompanha um único dia na vida de Naziazeno Barbosa, funcionário público em Porto Alegre que acorda com um problema aparentemente simples: pagar 53 mil-réis ao leiteiro até o dia seguinte, ou perder o fornecimento de leite para seu filho pequeno, Mainho. A narrativa mergulha na angústia crescente do protagonista enquanto ele percorre ruas, repartições, bancos e cafés em busca de um empréstimo que ninguém quer conceder — transformando uma dívida trivial num calvário psicológico sem fim.',
            resumo_en:
                "The novel follows a single day in the life of Naziazeno Barbosa, a civil servant in Porto Alegre who wakes up with a seemingly simple problem: paying 53 mil-réis to the milkman by the next morning, or losing the milk supply for his young son, Mainho. The narrative plunges into the protagonist's mounting anguish as he wanders streets, government offices, banks, and cafés in search of a loan no one will grant — turning a trivial debt into an unending psychological ordeal.",

            contexto:
                'A história se passa no centro de Porto Alegre dos anos 1930, cenário marcado pela Grande Depressão, pela instabilidade política da Era Vargas e pela ascensão de regimes autoritários. Dyonélio retrata a precariedade da classe média baixa urbana num momento em que a prosa regionalista dominava a cena literária brasileira — e opta deliberadamente pelo ambiente da cidade e pelo drama do assalariado anônimo.',
            contexto_en:
                'The story is set in downtown Porto Alegre in the 1930s, a backdrop shaped by the Great Depression, the political instability of the Vargas era, and the rise of authoritarian regimes. Dyonélio portrays the precariousness of the urban lower middle class at a time when regionalist rural prose dominated Brazilian fiction — deliberately choosing the city and the plight of the anonymous wage earner instead.',

            estiloEscrita:
                'Linguagem direta, seca e econômica, composta de frases curtas que imitam a velocidade e a vertigem do pensamento ansioso. O narrador onisciente alterna discurso indireto livre e discurso direto, acompanhando de perto o fluxo mental de Naziazeno. Dyonélio usa repetições rítmicas ("confabula, confabula"), reticências em excesso e a zoomorfização — substituindo palavras como "face" por "focinho" — para aproximar o homem da figura do rato. Cada um dos 28 capítulos curtos carrega sua própria célula de suspense, resolvida no máximo no capítulo seguinte, mantendo o leitor em estado permanente de tensão.',
            estiloEscrita_en:
                'The language is direct, dry, and economical — short sentences that mimic the speed and vertigo of anxious thought. An omniscient narrator alternates between free indirect discourse and direct speech, closely tracking Naziazeno\'s mental flow. Dyonélio uses rhythmic repetitions, excessive ellipses, and zoomorphization — replacing words like "face" with "snout" — to blur the line between the man and the rat. Each of the 28 short chapters carries its own cell of suspense, resolved at most in the next one, keeping the reader in a constant state of tension.',

            enredo: 'Avisada pelo leiteiro de que a dívida precisa ser quitada até o dia seguinte, Adelaide repassa o problema ao marido. Naziazeno passa então o dia inteiro percorrendo o centro de Porto Alegre — praças, repartições, bancos, botecos — tentando empréstimos com colegas, agiotas e superiores. A cada porta fechada, o desespero se aprofunda e o tempo psicológico se dilata. No limite, consegue penhorar uma joia de um amigo chamado Duque e paga o leiteiro. Mas o desfecho oferece apenas um alívio irônico: ao deitar, Naziazeno não consegue dormir, convencido de que ratos estão roendo o dinheiro que reservou. Ao amanhecer, os mesmos problemas o esperam.',
            enredo_en:
                "Warned by the milkman that the debt must be paid by the next morning, Adelaide passes the problem on to her husband. Naziazeno then spends the entire day crossing downtown Porto Alegre — squares, government offices, banks, and bars — trying to borrow money from colleagues, moneylenders, and superiors. Each closed door deepens his despair and stretches psychological time. At the last moment, he pawns a friend's jewelry and pays the milkman. But the ending offers only bitter irony: lying down, Naziazeno cannot sleep, convinced rats are gnawing at the money he set aside. At dawn, the same problems await him.",

            verossimilhanca:
                'Dyonélio ancora a narrativa em locais reais de Porto Alegre — a Praça da Alfândega, o Mercado Público, o Café Nacional, o New York Bank — criando uma topografia urbana concreta e reconhecível. A minúcia psicológica com que descreve gestos como sacudir moedas no bolso, cortar nervosamente um pão em migalhas ou estudar como abordar um superior confere à obra um realismo que ultrapassa o documental: o leitor sente a humilhação e o cansaço de Naziazeno como experiências físicas.',
            verossimilhanca_en:
                "Dyonélio anchors the narrative in real Porto Alegre locations — Praça da Alfândega, the Public Market, Café Nacional, the New York Bank — creating a concrete, recognizable urban topography. The psychological minuteness with which he describes gestures like jingling coins in a pocket, nervously crumbling bread, or rehearsing how to approach a superior gives the novel a realism that goes beyond the documentary: the reader feels Naziazeno's humiliation and exhaustion as physical sensations.",

            personagens: [
                'Naziazeno Barbosa',
                'Adelaide',
                'Mainho',
                'O Leiteiro',
                'Dr. Romeiro',
                'Alcides',
                'Duque',
                'Costa Miranda',
            ],

            caracteristicasLiterarias:
                'Pertencente à segunda fase do Modernismo brasileiro, o romance se destaca pelo uso do tempo psicológico em oposição ao tempo cronológico; pela crítica ao capitalismo e à alienação urbana; pela influência direta da psicanálise freudiana na construção do protagonista; pela ausência de heróis ou momentos sublimes — apenas a mediocridade e a fragmentação do cotidiano. A comparação com Dostoiévski é frequente na crítica: assim como Raskólnikov em Crime e Castigo, Naziazeno é um homem comum empurrado para um abismo de angústia e impotência. O romance ganhou o Prêmio Machado de Assis da Academia Brasileira de Letras.',
            caracteristicasLiterarias_en:
                "Belonging to the second phase of Brazilian Modernism, the novel stands out for its use of psychological time versus chronological time; its critique of capitalism and urban alienation; the direct Freudian psychoanalytic influence on the protagonist's construction; and the absence of heroes or sublime moments — only the mediocrity and fragmentation of daily life. Critics frequently compare it to Dostoevsky: like Raskolnikov in Crime and Punishment, Naziazeno is an ordinary man pushed to the edge of anguish and powerlessness. The novel won the Machado de Assis Prize from the Brazilian Academy of Letters.",

            conclusao:
                'Os Ratos foi escrito em apenas 20 dias para um concurso, mas amadurecido durante nove anos. Quase um século depois de sua publicação, o romance permanece urgente: a topografia da humilhação financeira, o individualismo da cidade e a solidão do homem na multidão não envelheceram. A imagem final — Naziazeno acordado no escuro, ouvindo ratos que talvez não existam, protegendo um dinheiro que mal cobre a próxima dívida — é uma das mais perturbadoras da literatura brasileira.',
            conclusao_en:
                'The Rats was written in just 20 days for a competition, but had been maturing for nine years. Nearly a century after its publication, the novel remains urgent: the topography of financial humiliation, urban individualism, and the loneliness of a man lost in the crowd have not aged. The final image — Naziazeno awake in the dark, hearing rats that may not exist, guarding money that barely covers the next debt — is one of the most unsettling in Brazilian literature.',
        },
    });

    await prisma.personagem.createMany({
        data: [
            {
                nome: 'Adelaide',
                caracteristicas_pt: 'Preocupada, prática, direta, responsável e realista',
                caracteristicas_en:
                    'Worried, practical, straightforward, responsible and realistic',
                representacao_pt:
                    'Representa a realidade doméstica e a pressão familiar, sendo a voz da responsabilidade e da sobrevivência dentro do lar, além de evidenciar o impacto da pobreza nas relações familiares',
                representacao_en:
                    'Represents domestic reality and family pressure, acting as the voice of responsibility and survival within the household, also highlighting the impact of poverty on family relationships',
            },
            {
                nome: 'Duque',
                caracteristicas_pt:
                    'Astuto, manipulador, esperto, oportunista, sociável, persuasivo',
                caracteristicas_en:
                    'Cunning, manipulative, clever, opportunistic, sociable, persuasive',
                representacao_pt:
                    'Representa o indivíduo que se adapta ao sistema por meio da malandragem e da esperteza, simbolizando estratégias de sobrevivência em uma sociedade desigual',
                representacao_en:
                    'Represents the individual who adapts to the system through cunning and street-smart behavior, symbolizing survival strategies in an unequal society',
            },
            {
                nome: 'Alcides',
                caracteristicas_pt:
                    'Mais estável, aparentemente tranquilo, prático, menos emocional, observador',
                caracteristicas_en:
                    'More stable, apparently calm, practical, less emotional, observant',
                representacao_pt:
                    'Representa uma alternativa ao desespero de Naziazeno, simbolizando alguém mais adaptado à realidade, embora ainda inserido no mesmo contexto social difícil',
                representacao_en:
                    'Represents an alternative to Naziazeno’s despair, symbolizing someone more adapted to reality, although still within the same difficult social context',
            },
            {
                nome: 'Dona Rosa (leiteira)',
                caracteristicas_pt: 'Rígida, cobradora, direta, impaciente, prática',
                caracteristicas_en: 'Strict, demanding, direct, impatient, practical',
                representacao_pt:
                    'Representa a pressão econômica imediata e impessoal, simbolizando como as relações sociais são mediadas pelo dinheiro e pela necessidade de sobrevivência',
                representacao_en:
                    'Represents immediate and impersonal economic pressure, symbolizing how social relations are mediated by money and survival needs',
            },
        ],
    });

    // VideoAula
    await prisma.videoAula.createMany({
        data: [
            {
                conteudo: 'Aula sobre Revolução Francesa',
                content: 'Class about French Revolution',
                urlMidia: 'https://video1.com',
                descricao: 'Explicação completa',
                description: 'Full explanation',
            },
            {
                conteudo: 'Aula de Matemática',
                content: 'Math class',
                urlMidia: 'https://video2.com',
                descricao: 'Funções lineares',
                description: 'Linear functions',
            },
        ],
    });

    // Curiosidade
    await prisma.curiosidade.createMany({
        data: [
            {
                conteudo: 'Curiosidade sobre o espaço',
                content: 'Space curiosity',
                curiosidade: 'O Sol representa 99% da massa do sistema solar',
                curiosity: 'The Sun is 99% of solar system mass',
            },
            {
                conteudo: 'Curiosidade histórica',
                content: 'History curiosity',
                curiosidade: 'Napoleão não era tão baixo quanto dizem',
                curiosity: 'Napoleon was not that short',
            },
        ],
    });

    // Dicas
    await prisma.dicas.createMany({
        data: [
            {
                conteudo: 'Dica de estudo',
                content: 'Study tip',
                dicas: 'Estude 25 minutos e descanse 5',
                tips: 'Study 25 min, rest 5',
            },
            {
                conteudo: 'Dica de produtividade',
                content: 'Productivity tip',
                dicas: 'Evite multitarefa',
                tips: 'Avoid multitasking',
            },
        ],
    });

    // Simulado
    await prisma.simulado.createMany({
        data: [
            // --- BIOLOGIA ---
            {
                pergunta: 'Qual organela é responsável pela respiração celular?',
                question: 'Which organelle is responsible for cellular respiration?',
                opcaoA: 'Ribossomo',
                optionA: 'Ribosome',
                opcaoB: 'Complexo de Golgi',
                optionB: 'Golgi Apparatus',
                opcaoC: 'Mitocôndria',
                optionC: 'Mitochondria',
                opcaoD: 'Lisossomo',
                optionD: 'Lysosome',
                opcaoE: 'Cloroplasto',
                optionE: 'Chloroplast',
                respostaCorreta: 'Mitocôndria',
                correctAnswer: 'Mitochondria',
                explicacao: 'A mitocôndria produz ATP através do oxigênio.',
                explanation: 'Mitochondria produce ATP through oxygen.',
                materia: 'Biologia',
            },
            {
                pergunta:
                    'Qual o nome do processo de divisão celular que gera células filhas idênticas?',
                question:
                    'What is the name of the cell division process that creates identical daughter cells?',
                opcaoA: 'Meiose',
                optionA: 'Meiosis',
                opcaoB: 'Fecundação',
                optionB: 'Fertilization',
                opcaoC: 'Mitose',
                optionC: 'Mitosis',
                opcaoD: 'Simbiose',
                optionD: 'Symbiosis',
                opcaoE: 'Osmose',
                optionE: 'Osmosis',
                respostaCorreta: 'Mitose',
                correctAnswer: 'Mitosis',
                explicacao: 'A mitose mantém o número de cromossomos constante.',
                explanation: 'Mitosis keeps the number of chromosomes constant.',
                materia: 'Biologia',
            },
            {
                pergunta: 'Quem é considerado o pai da genética?',
                question: 'Who is considered the father of genetics?',
                opcaoA: 'Darwin',
                optionA: 'Darwin',
                opcaoB: 'Mendel',
                optionB: 'Mendel',
                opcaoC: 'Lamarck',
                optionC: 'Lamarck',
                opcaoD: 'Linneu',
                optionD: 'Linnaeus',
                opcaoE: 'Pasteur',
                optionE: 'Pasteur',
                respostaCorreta: 'Mendel',
                correctAnswer: 'Mendel',
                explicacao: 'Gregor Mendel estudou a hereditariedade com ervilhas.',
                explanation: 'Gregor Mendel studied heredity with peas.',
                materia: 'Biologia',
            },
            {
                pergunta: 'Qual base nitrogenada não está presente no DNA?',
                question: 'Which nitrogenous base is not present in DNA?',
                opcaoA: 'Adenina',
                optionA: 'Adenine',
                opcaoB: 'Citosina',
                optionB: 'Cytosine',
                opcaoC: 'Guanina',
                optionC: 'Guanine',
                opcaoD: 'Uracila',
                optionD: 'Uracil',
                opcaoE: 'Timina',
                optionE: 'Thymine',
                respostaCorreta: 'Uracila',
                correctAnswer: 'Uracil',
                explicacao: 'A uracila é exclusiva do RNA.',
                explanation: 'Uracil is exclusive to RNA.',
                materia: 'Biologia',
            },
            {
                pergunta: 'O que define um organismo autótrofo?',
                question: 'What defines an autotrophic organism?',
                opcaoA: 'Produz seu próprio alimento',
                optionA: 'Produces its own food',
                opcaoB: 'Consome outros seres',
                optionB: 'Consumes other beings',
                opcaoC: 'É um parasita',
                optionC: 'It is a parasite',
                opcaoD: 'Não possui células',
                optionD: 'Does not have cells',
                opcaoE: 'Vive apenas na água',
                optionE: 'Lives only in water',
                respostaCorreta: 'Produz seu próprio alimento',
                correctAnswer: 'Produces its own food',
                explicacao: 'Autótrofos realizam fotossíntese ou quimiossíntese.',
                explanation: 'Autotrophs perform photosynthesis or chemosynthesis.',
                materia: 'Biologia',
            },
            {
                pergunta: 'Qual o principal gás responsável pelo efeito estufa?',
                question: 'What is the main gas responsible for the greenhouse effect?',
                opcaoA: 'Oxigênio',
                optionA: 'Oxygen',
                opcaoB: 'Nitrogênio',
                optionB: 'Nitrogen',
                opcaoC: 'Dióxido de Carbono',
                optionC: 'Carbon Dioxide',
                opcaoD: 'Argônio',
                optionD: 'Argon',
                opcaoE: 'Hélio',
                optionE: 'Helium',
                respostaCorreta: 'Dióxido de Carbono',
                correctAnswer: 'Carbon Dioxide',
                explicacao: 'O CO2 retém calor na atmosfera terrestre.',
                explanation: "CO2 traps heat in the Earth's atmosphere.",
                materia: 'Biologia',
            },
            {
                pergunta: 'Onde ocorre a troca gasosa no sistema respiratório humano?',
                question: 'Where does gas exchange occur in the human respiratory system?',
                opcaoA: 'Traqueia',
                optionA: 'Trachea',
                opcaoB: 'Laringe',
                optionB: 'Larynx',
                opcaoC: 'Alvéolos pulmonares',
                optionC: 'Pulmonary alveoli',
                opcaoD: 'Brônquios',
                optionD: 'Bronchi',
                opcaoE: 'Faringe',
                optionE: 'Pharynx',
                respostaCorreta: 'Alvéolos pulmonares',
                correctAnswer: 'Pulmonary alveoli',
                explicacao: 'A hematose ocorre nos alvéolos.',
                explanation: 'Hematosis occurs in the alveoli.',
                materia: 'Biologia',
            },
            {
                pergunta: 'Qual o maior órgão do corpo humano?',
                question: 'What is the largest organ of the human body?',
                opcaoA: 'Fígado',
                optionA: 'Liver',
                opcaoB: 'Coração',
                optionB: 'Heart',
                opcaoC: 'Pele',
                optionC: 'Skin',
                opcaoD: 'Pulmão',
                optionD: 'Lung',
                opcaoE: 'Intestino',
                optionE: 'Intestine',
                respostaCorreta: 'Pele',
                correctAnswer: 'Skin',
                explicacao: 'A pele é o órgão mais extenso do corpo.',
                explanation: 'The skin is the most extensive organ in the body.',
                materia: 'Biologia',
            },
            {
                pergunta: 'Como se chama o conjunto de indivíduos da mesma espécie em uma área?',
                question: 'What is a group of individuals of the same species in an area called?',
                opcaoA: 'Ecossistema',
                optionA: 'Ecosystem',
                opcaoB: 'Comunidade',
                optionB: 'Community',
                opcaoC: 'População',
                optionC: 'Population',
                opcaoD: 'Biosfera',
                optionD: 'Biosphere',
                opcaoE: 'Nicho',
                optionE: 'Niche',
                respostaCorreta: 'População',
                correctAnswer: 'Population',
                explicacao: 'População refere-se à mesma espécie no mesmo local.',
                explanation: 'Population refers to the same species in the same location.',
                materia: 'Biologia',
            },
            {
                pergunta: 'Qual vitamina é produzida pelo corpo ao se expor ao sol?',
                question: 'Which vitamin is produced by the body when exposed to the sun?',
                opcaoA: 'Vitamina A',
                optionA: 'Vitamin A',
                opcaoB: 'Vitamina C',
                optionB: 'Vitamin C',
                opcaoC: 'Vitamina K',
                optionC: 'Vitamin K',
                opcaoD: 'Vitamina D',
                optionD: 'Vitamin D',
                opcaoE: 'Vitamina B12',
                optionE: 'Vitamin B12',
                respostaCorreta: 'Vitamina D',
                correctAnswer: 'Vitamin D',
                explicacao: 'A luz UV ativa a síntese de Vitamina D na pele.',
                explanation: 'UV light activates Vitamin D synthesis in the skin.',
                materia: 'Biologia',
            },

            // --- FÍSICA ---
            {
                pergunta: 'Qual a unidade de medida da força no Sistema Internacional?',
                question: 'What is the unit of measurement for force in the International System?',
                opcaoA: 'Joule',
                optionA: 'Joule',
                opcaoB: 'Newton',
                optionB: 'Newton',
                opcaoC: 'Watt',
                optionC: 'Watt',
                opcaoD: 'Pascal',
                optionD: 'Pascal',
                opcaoE: 'Volt',
                optionE: 'Volt',
                respostaCorreta: 'Newton',
                correctAnswer: 'Newton',
                explicacao: 'A força é medida em Newtons (N), em homenagem a Isaac Newton.',
                explanation: 'Force is measured in Newtons (N), named after Isaac Newton.',
                materia: 'Física',
            },
            {
                pergunta: 'Qual a velocidade da luz no vácuo?',
                question: 'What is the speed of light in a vacuum?',
                opcaoA: '300.000 km/s',
                optionA: '300,000 km/s',
                opcaoB: '150.000 km/s',
                optionB: '150,000 km/s',
                opcaoC: '1.000 km/s',
                optionC: '1,000 km/s',
                opcaoD: '340 m/s',
                optionD: '340 m/s',
                opcaoE: '100.000 km/h',
                optionE: '100,000 km/h',
                respostaCorreta: '300.000 km/s',
                correctAnswer: '300,000 km/s',
                explicacao: 'A luz viaja aproximadamente a 300.000 km por segundo.',
                explanation: 'Light travels at approximately 300,000 km per second.',
                materia: 'Física',
            },
            {
                pergunta: 'Qual lei de Newton afirma que "toda ação tem uma reação"?',
                question: 'Which Newton law states that "every action has a reaction"?',
                opcaoA: 'Primeira Lei',
                optionA: 'First Law',
                opcaoB: 'Segunda Lei',
                optionB: 'Second Law',
                opcaoC: 'Terceira Lei',
                optionC: 'Third Law',
                opcaoD: 'Lei da Gravitação',
                optionD: 'Law of Gravitation',
                opcaoE: 'Lei da Inércia',
                optionE: 'Law of Inertia',
                respostaCorreta: 'Terceira Lei',
                correctAnswer: 'Third Law',
                explicacao: 'A Terceira Lei trata das forças de interação.',
                explanation: 'The Third Law deals with interaction forces.',
                materia: 'Física',
            },
            {
                pergunta: 'O que é o som?',
                question: 'What is sound?',
                opcaoA: 'Uma onda eletromagnética',
                optionA: 'An electromagnetic wave',
                opcaoB: 'Uma onda mecânica',
                optionB: 'A mechanical wave',
                opcaoC: 'Uma partícula',
                optionC: 'A particle',
                opcaoD: 'Um vácuo',
                optionD: 'A vacuum',
                opcaoE: 'Luz visível',
                optionE: 'Visible light',
                respostaCorreta: 'Uma onda mecânica',
                correctAnswer: 'A mechanical wave',
                explicacao: 'O som precisa de um meio material para se propagar.',
                explanation: 'Sound needs a material medium to propagate.',
                materia: 'Física',
            },
            {
                pergunta: 'Qual a temperatura de ebulição da água ao nível do mar?',
                question: 'What is the boiling point of water at sea level?',
                opcaoA: '50°C',
                optionA: '50°C',
                opcaoB: '100°C',
                optionB: '100°C',
                opcaoC: '0°C',
                optionC: '0°C',
                opcaoD: '273°C',
                optionD: '273°C',
                opcaoE: '373°C',
                optionE: '373°C',
                respostaCorreta: '100°C',
                correctAnswer: '100°C',
                explicacao: 'A 1 atm, a água ferve a 100 graus Celsius.',
                explanation: 'At 1 atm, water boils at 100 degrees Celsius.',
                materia: 'Física',
            },
            {
                pergunta: 'Qual o instrumento usado para medir a corrente elétrica?',
                question: 'What instrument is used to measure electrical current?',
                opcaoA: 'Voltímetro',
                optionA: 'Voltmeter',
                opcaoB: 'Termômetro',
                optionB: 'Thermometer',
                opcaoC: 'Amperímetro',
                optionC: 'Ammeter',
                opcaoD: 'Barômetro',
                optionD: 'Barometer',
                opcaoE: 'Ohmímetro',
                optionE: 'Ohmmeter',
                respostaCorreta: 'Amperímetro',
                correctAnswer: 'Ammeter',
                explicacao: 'Amperímetros medem a intensidade da corrente em Ampères.',
                explanation: 'Ammeters measure current intensity in Amperes.',
                materia: 'Física',
            },
            {
                pergunta: 'Quem formulou a Teoria da Relatividade?',
                question: 'Who formulated the Theory of Relativity?',
                opcaoA: 'Isaac Newton',
                optionA: 'Isaac Newton',
                opcaoB: 'Marie Curie',
                optionB: 'Marie Curie',
                opcaoC: 'Galileu Galilei',
                optionC: 'Galileo Galilei',
                opcaoD: 'Albert Einstein',
                optionD: 'Albert Einstein',
                opcaoE: 'Stephen Hawking',
                optionE: 'Stephen Hawking',
                respostaCorreta: 'Albert Einstein',
                correctAnswer: 'Albert Einstein',
                explicacao: 'Einstein publicou a relatividade geral e restrita.',
                explanation: 'Einstein published general and special relativity.',
                materia: 'Física',
            },
            {
                pergunta: 'O que a inércia representa?',
                question: 'What does inertia represent?',
                opcaoA: 'Aceleração constante',
                optionA: 'Constant acceleration',
                opcaoB: 'Resistência à mudança de movimento',
                optionB: 'Resistance to change in motion',
                opcaoC: 'Força da gravidade',
                optionC: 'Gravity force',
                opcaoD: 'Energia cinética',
                optionD: 'Kinetic energy',
                opcaoE: 'Fricção',
                optionE: 'Friction',
                respostaCorreta: 'Resistência à mudança de movimento',
                correctAnswer: 'Resistance to change in motion',
                explicacao: 'Inércia é a tendência de um corpo manter seu estado.',
                explanation: 'Inertia is the tendency of a body to maintain its state.',
                materia: 'Física',
            },
            {
                pergunta: 'Qual cor de luz visível tem a menor frequência?',
                question: 'Which color of visible light has the lowest frequency?',
                opcaoA: 'Violeta',
                optionA: 'Violet',
                opcaoB: 'Azul',
                optionB: 'Blue',
                opcaoC: 'Verde',
                optionC: 'Green',
                opcaoD: 'Amarelo',
                optionD: 'Yellow',
                opcaoE: 'Vermelho',
                optionE: 'Red',
                respostaCorreta: 'Vermelho',
                correctAnswer: 'Red',
                explicacao: 'O vermelho tem o maior comprimento e menor frequência.',
                explanation: 'Red has the longest wavelength and lowest frequency.',
                materia: 'Física',
            },
            {
                pergunta: 'O que é energia potencial gravitacional?',
                question: 'What is gravitational potential energy?',
                opcaoA: 'Energia do movimento',
                optionA: 'Energy of motion',
                opcaoB: 'Energia armazenada pela altura',
                optionB: 'Energy stored due to height',
                opcaoC: 'Energia do calor',
                optionC: 'Heat energy',
                opcaoD: 'Energia nuclear',
                optionD: 'Nuclear energy',
                opcaoE: 'Energia sonora',
                optionE: 'Sound energy',
                respostaCorreta: 'Energia armazenada pela altura',
                correctAnswer: 'Energy stored due to height',
                explicacao: 'Depende da massa, gravidade e altura (mgh).',
                explanation: 'It depends on mass, gravity, and height (mgh).',
                materia: 'Física',
            },

            // --- QUÍMICA ---
            {
                pergunta: 'Qual o pH de uma solução neutra a 25°C?',
                question: 'What is the pH of a neutral solution at 25°C?',
                opcaoA: '0',
                optionA: '0',
                opcaoB: '14',
                optionB: '14',
                opcaoC: '5',
                optionC: '5',
                opcaoD: '7',
                optionD: '7',
                opcaoE: '10',
                optionE: '10',
                respostaCorreta: '7',
                correctAnswer: '7',
                explicacao: 'O pH 7 representa a neutralidade química.',
                explanation: 'A pH of 7 represents chemical neutrality.',
                materia: 'Química',
            },
            {
                pergunta: 'Qual o elemento químico mais abundante no universo?',
                question: 'What is the most abundant chemical element in the universe?',
                opcaoA: 'Hélio',
                optionA: 'Helium',
                opcaoB: 'Oxigênio',
                optionB: 'Oxygen',
                opcaoC: 'Hidrogênio',
                optionC: 'Hydrogen',
                opcaoD: 'Carbono',
                optionD: 'Carbon',
                opcaoE: 'Ferro',
                optionE: 'Iron',
                respostaCorreta: 'Hidrogênio',
                correctAnswer: 'Hydrogen',
                explicacao: 'O Hidrogênio compõe cerca de 75% da massa elementar.',
                explanation: 'Hydrogen makes up about 75% of elemental mass.',
                materia: 'Química',
            },
            {
                pergunta: 'Como se chama a mudança do estado sólido para o gasoso?',
                question: 'What is the transition from solid to gas called?',
                opcaoA: 'Fusão',
                optionA: 'Fusion',
                opcaoB: 'Sublimação',
                optionB: 'Sublimation',
                opcaoC: 'Condensação',
                optionC: 'Condensation',
                opcaoD: 'Evaporação',
                optionD: 'Evaporation',
                opcaoE: 'Solidificação',
                optionE: 'Solidification',
                respostaCorreta: 'Sublimação',
                correctAnswer: 'Sublimation',
                explicacao: 'A sublimação pula a fase líquida.',
                explanation: 'Sublimation skips the liquid phase.',
                materia: 'Química',
            },
            {
                pergunta: 'Qual a fórmula química da água oxigenada?',
                question: 'What is the chemical formula for hydrogen peroxide?',
                opcaoA: 'H2O',
                optionA: 'H2O',
                opcaoB: 'HO2',
                optionB: 'HO2',
                opcaoC: 'H2O2',
                optionC: 'H2O2',
                opcaoD: '2HO',
                optionD: '2HO',
                opcaoE: 'H3O',
                optionE: 'H3O',
                respostaCorreta: 'H2O2',
                correctAnswer: 'H2O2',
                explicacao: 'A água oxigenada possui dois oxigênios.',
                explanation: 'Hydrogen peroxide has two oxygens.',
                materia: 'Química',
            },
            {
                pergunta: 'O que são isótopos?',
                question: 'What are isotopes?',
                opcaoA: 'Mesmo número de prótons',
                optionA: 'Same number of protons',
                opcaoB: 'Mesmo número de nêutrons',
                optionB: 'Same number of neutrons',
                opcaoC: 'Mesmo número de massa',
                optionC: 'Same mass number',
                opcaoD: 'Diferente número atômico',
                optionD: 'Different atomic number',
                opcaoE: 'Mesma cor',
                optionE: 'Same color',
                respostaCorreta: 'Mesmo número de prótons',
                correctAnswer: 'Same number of protons',
                explicacao: 'Isótopos são o mesmo elemento com massas diferentes.',
                explanation: 'Isotopes are the same element with different masses.',
                materia: 'Química',
            },
            {
                pergunta: 'Qual o metal que se apresenta líquido em temperatura ambiente?',
                question: 'Which metal is liquid at room temperature?',
                opcaoA: 'Ouro',
                optionA: 'Gold',
                opcaoB: 'Prata',
                optionB: 'Silver',
                opcaoC: 'Cobre',
                optionC: 'Copper',
                opcaoD: 'Mercúrio',
                optionD: 'Mercury',
                opcaoE: 'Chumbo',
                optionE: 'Lead',
                respostaCorreta: 'Mercúrio',
                correctAnswer: 'Mercury',
                explicacao: 'O mercúrio (Hg) é o único metal líquido nestas condições.',
                explanation: 'Mercury (Hg) is the only liquid metal under these conditions.',
                materia: 'Química',
            },
            {
                pergunta: 'O que é uma reação exotérmica?',
                question: 'What is an exothermic reaction?',
                opcaoA: 'Absorve calor',
                optionA: 'Absorbs heat',
                opcaoB: 'Libera calor',
                optionB: 'Releases heat',
                opcaoC: 'Cria matéria',
                optionC: 'Creates matter',
                opcaoD: 'Não altera temperatura',
                optionD: 'Does not change temperature',
                opcaoE: 'Ocorre no vácuo',
                optionE: 'Occurs in a vacuum',
                respostaCorreta: 'Libera calor',
                correctAnswer: 'Releases heat',
                explicacao: 'Reações exotérmicas liberam energia para o ambiente.',
                explanation: 'Exothermic reactions release energy into the environment.',
                materia: 'Química',
            },
            {
                pergunta: 'Quantos elétrons o Oxigênio tem na camada de valência?',
                question: 'How many electrons does Oxygen have in its valence shell?',
                opcaoA: '2',
                optionA: '2',
                opcaoB: '4',
                optionB: '4',
                opcaoC: '6',
                optionC: '6',
                opcaoD: '8',
                optionD: '8',
                opcaoE: '1',
                optionE: '1',
                respostaCorreta: '6',
                correctAnswer: '6',
                explicacao: 'O Oxigênio pertence à família 16 (6A).',
                explanation: 'Oxygen belongs to group 16 (6A).',
                materia: 'Química',
            },
            {
                pergunta: 'Qual o símbolo químico do Ouro?',
                question: 'What is the chemical symbol for Gold?',
                opcaoA: 'Or',
                optionA: 'Or',
                opcaoB: 'Gd',
                optionB: 'Gd',
                opcaoC: 'Au',
                optionC: 'Au',
                opcaoD: 'Ag',
                optionD: 'Ag',
                opcaoE: 'Fe',
                optionE: 'Fe',
                respostaCorreta: 'Au',
                correctAnswer: 'Au',
                explicacao: 'Vem do latim "Aurum".',
                explanation: 'Comes from the Latin "Aurum".',
                materia: 'Química',
            },
            {
                pergunta: 'O que caracteriza uma ligação covalente?',
                question: 'What characterizes a covalent bond?',
                opcaoA: 'Transferência de elétrons',
                optionA: 'Transfer of electrons',
                opcaoB: 'Compartilhamento de elétrons',
                optionB: 'Sharing of electrons',
                opcaoC: 'Atração magnética',
                optionC: 'Magnetic attraction',
                opcaoD: 'Ligação entre metais',
                optionD: 'Bond between metals',
                opcaoE: 'Perda de prótons',
                optionE: 'Loss of protons',
                respostaCorreta: 'Compartilhamento de elétrons',
                correctAnswer: 'Sharing of electrons',
                explicacao: 'Ocorre entre não-metais compartilhando pares eletrônicos.',
                explanation: 'Occurs between non-metals sharing electronic pairs.',
                materia: 'Química',
            },

            // --- LÍNGUA PORTUGUESA ---
            {
                pergunta: 'Qual destas palavras é um hiato?',
                question: 'Which of these words contains a hiatus?',
                opcaoA: 'Caixa',
                optionA: 'Caixa',
                opcaoB: 'Peixe',
                optionB: 'Peixe',
                opcaoC: 'Saúde',
                optionC: 'Saúde',
                opcaoD: 'Noite',
                optionD: 'Noite',
                opcaoE: 'Pai',
                optionE: 'Pai',
                respostaCorreta: 'Saúde',
                correctAnswer: 'Saúde',
                explicacao: 'Em "Sa-ú-de", as vogais ficam em sílabas diferentes.',
                explanation: 'In "Sa-ú-de", the vowels stay in different syllables.',
                materia: 'Língua Portuguesa',
            },
            {
                pergunta: 'Quem escreveu "Dom Casmurro"?',
                question: 'Who wrote "Dom Casmurro"?',
                opcaoA: 'Eça de Queirós',
                optionA: 'Eça de Queirós',
                opcaoB: 'Jorge Amado',
                optionB: 'Jorge Amado',
                opcaoC: 'Machado de Assis',
                optionC: 'Machado de Assis',
                opcaoD: 'Clarice Lispector',
                optionD: 'Clarice Lispector',
                opcaoE: 'Guimarães Rosa',
                optionE: 'Guimarães Rosa',
                respostaCorreta: 'Machado de Assis',
                correctAnswer: 'Machado de Assis',
                explicacao: 'Machado de Assis é o autor deste clássico do Realismo.',
                explanation: 'Machado de Assis is the author of this Realism classic.',
                materia: 'Língua Portuguesa',
            },
            {
                pergunta: 'Qual a função do adjetivo na frase?',
                question: 'What is the function of the adjective in a sentence?',
                opcaoA: 'Indicar ação',
                optionA: 'Indicate action',
                opcaoB: 'Caracterizar o substantivo',
                optionB: 'Characterize the noun',
                opcaoC: 'Substituir o nome',
                optionC: 'Replace the name',
                opcaoD: 'Ligar orações',
                optionD: 'Connect sentences',
                opcaoE: 'Expressar emoção',
                optionE: 'Express emotion',
                respostaCorreta: 'Caracterizar o substantivo',
                correctAnswer: 'Characterize the noun',
                explicacao: 'Adjetivos atribuem qualidades ou estados.',
                explanation: 'Adjectives assign qualities or states.',
                materia: 'Língua Portuguesa',
            },
            {
                pergunta: 'Qual o plural de "Cidadão"?',
                question: 'What is the plural of "Cidadão" (Citizen)?',
                opcaoA: 'Cidadões',
                optionA: 'Cidadões',
                opcaoB: 'Cidadães',
                optionB: 'Cidadães',
                opcaoC: 'Cidadãos',
                optionC: 'Cidadãos',
                opcaoD: 'Cidãos',
                optionD: 'Cidãos',
                opcaoE: 'Cidadonés',
                optionE: 'Cidadonés',
                respostaCorreta: 'Cidadãos',
                correctAnswer: 'Cidadãos',
                explicacao: 'O plural correto termina em -ãos.',
                explanation: 'The correct plural ends in -ãos.',
                materia: 'Língua Portuguesa',
            },
            {
                pergunta: 'O que é um oxítona?',
                question: 'What is an "oxítona" (oxytone)?',
                opcaoA: 'Sílaba tônica é a última',
                optionA: 'Tonic syllable is the last one',
                opcaoB: 'Sílaba tônica é a penúltima',
                optionB: 'Tonic syllable is the second to last',
                opcaoC: 'Sílaba tônica é a antepenúltima',
                optionC: 'Tonic syllable is the third to last',
                opcaoD: 'Não tem sílaba tônica',
                optionD: 'Has no tonic syllable',
                opcaoE: 'Tem duas sílabas tônicas',
                optionE: 'Has two tonic syllables',
                respostaCorreta: 'Sílaba tônica é a última',
                correctAnswer: 'Tonic syllable is the last one',
                explicacao: 'Exemplos: café, amor, parabéns.',
                explanation: 'Examples: café, amor, parabéns.',
                materia: 'Língua Portuguesa',
            },
            {
                pergunta: 'Qual o antônimo de "Efémero"?',
                question: 'What is the antonym of "Ephemeral"?',
                opcaoA: 'Curto',
                optionA: 'Short',
                opcaoB: 'Passageiro',
                optionB: 'Passing',
                opcaoC: 'Duradouro',
                optionC: 'Long-lasting',
                opcaoD: 'Rápido',
                optionD: 'Fast',
                opcaoE: 'Belo',
                optionE: 'Beautiful',
                respostaCorreta: 'Duradouro',
                correctAnswer: 'Long-lasting',
                explicacao: 'Efémero é o que dura pouco; duradouro é o oposto.',
                explanation: 'Ephemeral is what lasts a short time; lasting is the opposite.',
                materia: 'Língua Portuguesa',
            },
            {
                pergunta: 'Identifique o sujeito: "Comeram o bolo as crianças."',
                question: 'Identify the subject: "The children ate the cake."',
                opcaoA: 'Comeram',
                optionA: 'Ate',
                opcaoB: 'Bolo',
                optionB: 'Cake',
                opcaoC: 'As crianças',
                optionC: 'The children',
                opcaoD: 'Inexistente',
                optionD: 'Non-existent',
                opcaoE: 'Oculto',
                optionE: 'Hidden',
                respostaCorreta: 'As crianças',
                correctAnswer: 'The children',
                explicacao: 'O sujeito está posposto ao verbo.',
                explanation: 'The subject is placed after the verb.',
                materia: 'Língua Portuguesa',
            },
            {
                pergunta: 'O que é uma metáfora?',
                question: 'What is a metaphor?',
                opcaoA: 'Repetição de sons',
                optionA: 'Repetition of sounds',
                opcaoB: 'Comparação implícita',
                optionB: 'Implicit comparison',
                opcaoC: 'Exagero intencional',
                optionC: 'Intentional exaggeration',
                opcaoD: 'Oposição de ideias',
                optionD: 'Opposition of ideas',
                opcaoE: 'Suavização de termo',
                optionE: 'Softening of a term',
                respostaCorreta: 'Comparação implícita',
                correctAnswer: 'Implicit comparison',
                explicacao: 'É uma figura de linguagem de comparação sem o conectivo "como".',
                explanation:
                    'It is a figure of speech of comparison without the connective "like".',
                materia: 'Língua Portuguesa',
            },
            {
                pergunta: 'Qual o coletivo de "Lobos"?',
                question: 'What is the collective noun for "Wolves"?',
                opcaoA: 'Enxame',
                optionA: 'Swarm',
                opcaoB: 'Cardume',
                optionB: 'School',
                opcaoC: 'Alcateia',
                optionC: 'Pack',
                opcaoD: 'Rebanho',
                optionD: 'Flock',
                opcaoE: 'Manada',
                optionE: 'Herd',
                respostaCorreta: 'Alcateia',
                correctAnswer: 'Pack',
                explicacao: 'Alcateia é o grupo de lobos.',
                explanation: 'Pack is the group of wolves.',
                materia: 'Língua Portuguesa',
            },
            {
                pergunta: 'A vírgula antes de "mas" é:',
                question: 'The comma before "but" (mas) is:',
                opcaoA: 'Obrigatória',
                optionA: 'Mandatory',
                opcaoB: 'Proibida',
                optionB: 'Forbidden',
                opcaoC: 'Facultativa',
                optionC: 'Optional',
                opcaoD: 'Apenas no final da frase',
                optionD: 'Only at the end of the sentence',
                opcaoE: 'Usa-se apenas em poesia',
                optionE: 'Used only in poetry',
                respostaCorreta: 'Obrigatória',
                correctAnswer: 'Mandatory',
                explicacao: 'Conjunções adversativas exigem vírgula antes.',
                explanation: 'Adversative conjunctions require a comma before.',
                materia: 'Língua Portuguesa',
            },

            // --- MATEMÁTICA ---
            {
                pergunta: 'Qual o valor de pi (aproximado)?',
                question: 'What is the value of pi (approximate)?',
                opcaoA: '3,14',
                optionA: '3.14',
                opcaoB: '2,17',
                optionB: '2.17',
                opcaoC: '1,41',
                optionC: '1.41',
                opcaoD: '0,50',
                optionD: '0.50',
                opcaoE: '3,80',
                optionE: '3.80',
                respostaCorreta: '3,14',
                correctAnswer: '3.14',
                explicacao: 'Pi é a razão entre a circunferência e o diâmetro.',
                explanation: "Pi is the ratio of a circle's circumference to its diameter.",
                materia: 'Matemática',
            },
            {
                pergunta: 'Quanto é 7 x 8?',
                question: 'How much is 7 x 8?',
                opcaoA: '54',
                optionA: '54',
                opcaoB: '56',
                optionB: '56',
                opcaoC: '62',
                optionC: '62',
                opcaoD: '49',
                optionD: '49',
                opcaoE: '64',
                optionE: '64',
                respostaCorreta: '56',
                correctAnswer: '56',
                explicacao: 'Cálculo básico de tabuada.',
                explanation: 'Basic multiplication table calculation.',
                materia: 'Matemática',
            },
            {
                pergunta: 'Qual o valor da raiz quadrada de 144?',
                question: 'What is the square root of 144?',
                opcaoA: '10',
                optionA: '10',
                opcaoB: '11',
                optionB: '11',
                opcaoC: '12',
                optionC: '12',
                opcaoD: '14',
                optionD: '14',
                opcaoE: '16',
                optionE: '16',
                respostaCorreta: '12',
                correctAnswer: '12',
                explicacao: '12 vezes 12 é igual a 144.',
                explanation: '12 times 12 equals 144.',
                materia: 'Matemática',
            },
            {
                pergunta: 'O que é um triângulo isósceles?',
                question: 'What is an isosceles triangle?',
                opcaoA: '3 lados iguais',
                optionA: '3 equal sides',
                opcaoB: '2 lados iguais',
                optionB: '2 equal sides',
                opcaoC: 'Nenhum lado igual',
                optionC: 'No equal sides',
                opcaoD: 'Um ângulo de 90 graus',
                optionD: 'One 90 degree angle',
                opcaoE: 'Um círculo',
                optionE: 'A circle',
                respostaCorreta: '2 lados iguais',
                correctAnswer: '2 equal sides',
                explicacao: 'Isósceles possui dois lados com a mesma medida.',
                explanation: 'Isosceles has two sides of the same length.',
                materia: 'Matemática',
            },
            {
                pergunta: 'Qual a soma dos ângulos internos de um triângulo?',
                question: 'What is the sum of the internal angles of a triangle?',
                opcaoA: '90°',
                optionA: '90°',
                opcaoB: '180°',
                optionB: '180°',
                opcaoC: '360°',
                optionC: '360°',
                opcaoD: '270°',
                optionD: '270°',
                opcaoE: '120°',
                optionE: '120°',
                respostaCorreta: '180°',
                correctAnswer: '180°',
                explicacao: 'A soma é sempre 180 graus em geometria euclidiana.',
                explanation: 'The sum is always 180 degrees in Euclidean geometry.',
                materia: 'Matemática',
            },
            {
                pergunta: 'O que é um número primo?',
                question: 'What is a prime number?',
                opcaoA: 'Divisível apenas por 1 e por ele mesmo',
                optionA: 'Divisible only by 1 and itself',
                opcaoB: 'Qualquer número par',
                optionB: 'Any even number',
                opcaoC: 'Múltiplo de 5',
                optionC: 'Multiple of 5',
                opcaoD: 'Número negativo',
                optionD: 'Negative number',
                opcaoE: 'Número que termina em zero',
                optionE: 'Number ending in zero',
                respostaCorreta: 'Divisível apenas por 1 e por ele mesmo',
                correctAnswer: 'Divisible only by 1 and itself',
                explicacao: 'Primos têm exatamente dois divisores.',
                explanation: 'Primes have exactly two divisors.',
                materia: 'Matemática',
            },
            {
                pergunta: 'Qual a fórmula da área de um círculo?',
                question: 'What is the formula for the area of a circle?',
                opcaoA: '2 * pi * r',
                optionA: '2 * pi * r',
                opcaoB: 'pi * r^2',
                optionB: 'pi * r^2',
                opcaoC: 'base * altura',
                optionC: 'base * height',
                opcaoD: 'lado^2',
                optionD: 'side^2',
                opcaoE: 'r^3',
                optionE: 'r^3',
                respostaCorreta: 'pi * r^2',
                correctAnswer: 'pi * r^2',
                explicacao: 'A área é pi vezes o raio ao quadrado.',
                explanation: 'The area is pi times the radius squared.',
                materia: 'Matemática',
            },
            {
                pergunta: 'Se x + 5 = 12, qual o valor de x?',
                question: 'If x + 5 = 12, what is the value of x?',
                opcaoA: '5',
                optionA: '5',
                opcaoB: '17',
                optionB: '17',
                opcaoC: '7',
                optionC: '7',
                opcaoD: '8',
                optionD: '8',
                opcaoE: '6',
                optionE: '6',
                respostaCorreta: '7',
                correctAnswer: '7',
                explicacao: '12 - 5 = 7.',
                explanation: '12 - 5 = 7.',
                materia: 'Matemática',
            },
            {
                pergunta: 'Qual o próximo número na sequência: 2, 4, 8, 16...?',
                question: 'What is the next number in the sequence: 2, 4, 8, 16...?',
                opcaoA: '20',
                optionA: '20',
                opcaoB: '32',
                optionB: '32',
                opcaoC: '24',
                optionC: '24',
                opcaoD: '18',
                optionD: '18',
                opcaoE: '64',
                optionE: '64',
                respostaCorreta: '32',
                correctAnswer: '32',
                explicacao: 'A sequência dobra a cada passo.',
                explanation: 'The sequence doubles at each step.',
                materia: 'Matemática',
            },
            {
                pergunta: 'O que é o teorema de Pitágoras?',
                question: 'What is the Pythagorean theorem?',
                opcaoA: 'a^2 = b^2 + c^2',
                optionA: 'a^2 = b^2 + c^2',
                opcaoB: 'a = b + c',
                optionB: 'a = b + c',
                opcaoC: 'e = mc^2',
                optionC: 'e = mc^2',
                opcaoD: 'f = m * a',
                optionD: 'f = m * a',
                opcaoE: 'v = d / t',
                optionE: 'v = d / t',
                respostaCorreta: 'a^2 = b^2 + c^2',
                correctAnswer: 'a^2 = b^2 + c^2',
                explicacao: 'Relaciona os lados de um triângulo retângulo.',
                explanation: 'Relates the sides of a right triangle.',
                materia: 'Matemática',
            },

            // --- ARTES ---
            {
                pergunta: 'Quem pintou a "Mona Lisa"?',
                question: 'Who painted the "Mona Lisa"?',
                opcaoA: 'Van Gogh',
                optionA: 'Van Gogh',
                opcaoB: 'Picasso',
                optionB: 'Picasso',
                opcaoC: 'Leonardo da Vinci',
                optionC: 'Leonardo da Vinci',
                opcaoD: 'Salvador Dalí',
                optionD: 'Salvador Dalí',
                opcaoE: 'Claude Monet',
                optionE: 'Claude Monet',
                respostaCorreta: 'Leonardo da Vinci',
                correctAnswer: 'Leonardo da Vinci',
                explicacao: 'A obra é uma das mais famosas de Da Vinci.',
                explanation: "The work is one of Da Vinci's most famous.",
                materia: 'Artes',
            },
            {
                pergunta: 'Qual movimento artístico foca em pontos de cor?',
                question: 'Which art movement focuses on dots of color?',
                opcaoA: 'Surrealismo',
                optionA: 'Surrealism',
                opcaoB: 'Pontilhismo',
                optionB: 'Pointillism',
                opcaoC: 'Cubismo',
                optionC: 'Cubism',
                opcaoD: 'Barroco',
                optionD: 'Baroque',
                opcaoE: 'Pop Art',
                optionE: 'Pop Art',
                respostaCorreta: 'Pontilhismo',
                correctAnswer: 'Pointillism',
                explicacao: 'O pontilhismo utiliza pequenos pontos para formar imagens.',
                explanation: 'Pointillism uses small dots to form images.',
                materia: 'Artes',
            },
            {
                pergunta: 'Quem pintou "O Grito"?',
                question: 'Who painted "The Scream"?',
                opcaoA: 'Edvard Munch',
                optionA: 'Edvard Munch',
                opcaoB: 'Andy Warhol',
                optionB: 'Andy Warhol',
                opcaoC: 'Frida Kahlo',
                optionC: 'Frida Kahlo',
                opcaoD: 'Tarsila do Amaral',
                optionD: 'Tarsila do Amaral',
                opcaoE: 'Michelangelo',
                optionE: 'Michelangelo',
                respostaCorreta: 'Edvard Munch',
                correctAnswer: 'Edvard Munch',
                explicacao: 'Munch é um ícone do Expressionismo.',
                explanation: 'Munch is an icon of Expressionism.',
                materia: 'Artes',
            },
            {
                pergunta: 'Qual o estilo da Capela Sistina?',
                question: 'What is the style of the Sistine Chapel?',
                opcaoA: 'Gótico',
                optionA: 'Gothic',
                opcaoB: 'Renascentista',
                optionB: 'Renaissance',
                opcaoC: 'Modernista',
                optionC: 'Modernist',
                opcaoD: 'Rococó',
                optionD: 'Rococo',
                opcaoE: 'Abstrato',
                optionE: 'Abstract',
                respostaCorreta: 'Renascentista',
                correctAnswer: 'Renaissance',
                explicacao: 'Foi pintada por Michelangelo no auge do Renascimento.',
                explanation: 'It was painted by Michelangelo at the height of the Renaissance.',
                materia: 'Artes',
            },
            {
                pergunta: 'O que caracteriza o Cubismo?',
                question: 'What characterizes Cubism?',
                opcaoA: 'Uso de formas geométricas',
                optionA: 'Use of geometric shapes',
                opcaoB: 'Pintura ao ar livre',
                optionB: 'Outdoor painting',
                opcaoC: 'Foco no subconsciente',
                optionC: 'Focus on the subconscious',
                opcaoD: 'Excesso de detalhes dourados',
                optionD: 'Excess of gold details',
                opcaoE: 'Uso exclusivo de preto e branco',
                optionE: 'Exclusive use of black and white',
                respostaCorreta: 'Uso de formas geométricas',
                correctAnswer: 'Use of geometric shapes',
                explicacao: 'Picasso e Braque fragmentavam a realidade em cubos.',
                explanation: 'Picasso and Braque fragmented reality into cubes.',
                materia: 'Artes',
            },
            {
                pergunta: 'Quem é o principal nome da Pop Art?',
                question: 'Who is the main name of Pop Art?',
                opcaoA: 'Banksy',
                optionA: 'Banksy',
                opcaoB: 'Andy Warhol',
                optionB: 'Andy Warhol',
                opcaoC: 'Dali',
                optionC: 'Dali',
                opcaoD: 'Rodin',
                optionD: 'Rodin',
                opcaoE: 'Bernini',
                optionE: 'Bernini',
                respostaCorreta: 'Andy Warhol',
                correctAnswer: 'Andy Warhol',
                explicacao: 'Warhol é famoso pelas latas de sopa e retratos de Marilyn Monroe.',
                explanation: 'Warhol is famous for soup cans and Marilyn Monroe portraits.',
                materia: 'Artes',
            },
            {
                pergunta: 'Qual destas é uma cor primária?',
                question: 'Which of these is a primary color?',
                opcaoA: 'Verde',
                optionA: 'Green',
                opcaoB: 'Roxo',
                optionB: 'Purple',
                opcaoC: 'Azul',
                optionC: 'Blue',
                opcaoD: 'Laranja',
                optionD: 'Orange',
                opcaoE: 'Rosa',
                optionE: 'Pink',
                respostaCorreta: 'Azul',
                correctAnswer: 'Blue',
                explicacao: 'As cores primárias RYB são Vermelho, Amarelo e Azul.',
                explanation: 'The RYB primary colors are Red, Yellow, and Blue.',
                materia: 'Artes',
            },
            {
                pergunta: 'Quem esculpiu "David"?',
                question: 'Who sculpted "David"?',
                opcaoA: 'Michelangelo',
                optionA: 'Michelangelo',
                opcaoB: 'Donatello',
                optionB: 'Donatello',
                opcaoC: 'Rafael',
                optionC: 'Raphael',
                opcaoD: 'Botero',
                optionD: 'Botero',
                opcaoE: 'Gaudi',
                optionE: 'Gaudi',
                respostaCorreta: 'Michelangelo',
                correctAnswer: 'Michelangelo',
                explicacao: 'Michelangelo esculpiu o David de mármore.',
                explanation: 'Michelangelo sculpted the marble David.',
                materia: 'Artes',
            },
            {
                pergunta: 'O que foi a Semana de Arte Moderna?',
                question: 'What was the Modern Art Week?',
                opcaoA: 'Evento em Paris em 1900',
                optionA: 'Event in Paris in 1900',
                opcaoB: 'Marco do Modernismo no Brasil (1922)',
                optionB: 'Modernism landmark in Brazil (1922)',
                opcaoC: 'Uma exposição de arte sacra',
                optionC: 'An exhibition of sacred art',
                opcaoD: 'Inauguração do Louvre',
                optionD: 'Opening of the Louvre',
                opcaoE: 'Feira de artesanato',
                optionE: 'Craft fair',
                respostaCorreta: 'Marco do Modernismo no Brasil (1922)',
                correctAnswer: 'Modernism landmark in Brazil (1922)',
                explicacao: 'Ocorreu no Teatro Municipal de São Paulo.',
                explanation: 'It took place at the Municipal Theater of São Paulo.',
                materia: 'Artes',
            },
            {
                pergunta: 'O que é "Grafite"?',
                question: 'What is "Graffiti"?',
                opcaoA: 'Apenas vandalismo',
                optionA: 'Just vandalism',
                opcaoB: 'Manifestação artística em espaços públicos',
                optionB: 'Artistic manifestation in public spaces',
                opcaoC: 'Tipo de pintura em tela',
                optionC: 'Type of painting on canvas',
                opcaoD: 'Escultura em metal',
                optionD: 'Metal sculpture',
                opcaoE: 'Dança clássica',
                optionE: 'Classical dance',
                respostaCorreta: 'Manifestação artística em espaços públicos',
                correctAnswer: 'Artistic manifestation in public spaces',
                explicacao: 'O grafite é uma forma de arte urbana.',
                explanation: 'Graffiti is a form of urban art.',
                materia: 'Artes',
            },

            // --- GEOGRAFIA ---
            {
                pergunta: 'Qual o maior oceano do planeta?',
                question: 'What is the largest ocean on the planet?',
                opcaoA: 'Atlântico',
                optionA: 'Atlantic',
                opcaoB: 'Índico',
                optionB: 'Indian',
                opcaoC: 'Ártico',
                optionC: 'Arctic',
                opcaoD: 'Pacífico',
                optionD: 'Pacific',
                opcaoE: 'Antártico',
                optionE: 'Antarctic',
                respostaCorreta: 'Pacífico',
                correctAnswer: 'Pacific',
                explicacao: 'O Pacífico cobre um terço da superfície da Terra.',
                explanation: "The Pacific covers one-third of the Earth's surface.",
                materia: 'Geografia',
            },
            {
                pergunta: 'Qual a maior floresta tropical do mundo?',
                question: 'What is the largest tropical rainforest in the world?',
                opcaoA: 'Congo',
                optionA: 'Congo',
                opcaoB: 'Taiga',
                optionB: 'Taiga',
                opcaoC: 'Amazônia',
                optionC: 'Amazon',
                opcaoD: 'Mata Atlântica',
                optionD: 'Atlantic Forest',
                opcaoE: 'Savana',
                optionE: 'Savannah',
                respostaCorreta: 'Amazônia',
                correctAnswer: 'Amazon',
                explicacao: 'A Amazônia abrange nove países da América do Sul.',
                explanation: 'The Amazon spans nine South American countries.',
                materia: 'Geografia',
            },
            {
                pergunta: 'Qual o país mais populoso do mundo?',
                question: 'What is the most populous country in the world?',
                opcaoA: 'EUA',
                optionA: 'USA',
                opcaoB: 'Índia',
                optionB: 'India',
                opcaoC: 'China',
                optionC: 'China',
                opcaoD: 'Brasil',
                optionD: 'Brazil',
                opcaoE: 'Rússia',
                optionE: 'Russia',
                respostaCorreta: 'Índia',
                correctAnswer: 'India',
                explicacao: 'A Índia ultrapassou a China recentemente.',
                explanation: 'India recently surpassed China.',
                materia: 'Geografia',
            },
            {
                pergunta: 'Qual linha imaginária divide a Terra em Norte e Sul?',
                question: 'Which imaginary line divides the Earth into North and South?',
                opcaoA: 'Meridiano de Greenwich',
                optionA: 'Greenwich Meridian',
                opcaoB: 'Trópico de Câncer',
                optionB: 'Tropic of Cancer',
                opcaoC: 'Equador',
                optionC: 'Equator',
                opcaoD: 'Círculo Polar',
                optionD: 'Polar Circle',
                opcaoE: 'Trópico de Capricórnio',
                optionE: 'Tropic of Capricorn',
                respostaCorreta: 'Equador',
                correctAnswer: 'Equator',
                explicacao: 'O Equador é o marco zero da latitude.',
                explanation: 'The Equator is the zero point of latitude.',
                materia: 'Geografia',
            },
            {
                pergunta: 'Onde se localiza o Deserto do Saara?',
                question: 'Where is the Sahara Desert located?',
                opcaoA: 'Ásia',
                optionA: 'Asia',
                opcaoB: 'América do Sul',
                optionB: 'South America',
                opcaoC: 'África',
                optionC: 'Africa',
                opcaoD: 'Austrália',
                optionD: 'Australia',
                opcaoE: 'Europa',
                optionE: 'Europe',
                respostaCorreta: 'África',
                correctAnswer: 'Africa',
                explicacao: 'Fica no norte do continente africano.',
                explanation: 'It is in the north of the African continent.',
                materia: 'Geografia',
            },
            {
                pergunta: 'Qual o maior país em extensão territorial?',
                question: 'What is the largest country by land area?',
                opcaoA: 'Canadá',
                optionA: 'Canada',
                opcaoB: 'China',
                optionB: 'China',
                opcaoC: 'Rússia',
                optionC: 'Russia',
                opcaoD: 'EUA',
                optionD: 'USA',
                opcaoE: 'Austrália',
                optionE: 'Australia',
                respostaCorreta: 'Rússia',
                correctAnswer: 'Russia',
                explicacao: 'A Rússia ocupa vasta área na Europa e Ásia.',
                explanation: 'Russia occupies a vast area in Europe and Asia.',
                materia: 'Geografia',
            },
            {
                pergunta: 'O que é o PIB?',
                question: 'What is GDP?',
                opcaoA: 'População Interna Bruta',
                optionA: 'Gross Internal Population',
                opcaoB: 'Produto Interno Bruto',
                optionB: 'Gross Domestic Product',
                opcaoC: 'Preço Industrial Baixo',
                optionC: 'Low Industrial Price',
                opcaoD: 'Plano de Investimento Brasil',
                optionD: 'Brazil Investment Plan',
                opcaoE: 'Ponto de Interesse Bancário',
                optionE: 'Banking Interest Point',
                respostaCorreta: 'Produto Interno Bruto',
                correctAnswer: 'Gross Domestic Product',
                explicacao: 'Soma de todos os bens e serviços produzidos.',
                explanation: 'Sum of all goods and services produced.',
                materia: 'Geografia',
            },
            {
                pergunta: 'Qual o monte mais alto do mundo?',
                question: 'What is the highest mountain in the world?',
                opcaoA: 'K2',
                optionA: 'K2',
                opcaoB: 'Kilimanjaro',
                optionB: 'Kilimanjaro',
                opcaoC: 'Everest',
                optionC: 'Everest',
                opcaoD: 'Aconcágua',
                optionD: 'Aconcagua',
                opcaoE: 'Monte Branco',
                optionE: 'Mont Blanc',
                respostaCorreta: 'Everest',
                correctAnswer: 'Everest',
                explicacao: 'Localizado no Himalaia, com 8.848m.',
                explanation: 'Located in the Himalayas, at 8,848m.',
                materia: 'Geografia',
            },
            {
                pergunta: 'Qual o menor país do mundo?',
                question: 'What is the smallest country in the world?',
                opcaoA: 'Mônaco',
                optionA: 'Monaco',
                opcaoB: 'Vaticano',
                optionB: 'Vatican',
                opcaoC: 'Malta',
                optionC: 'Malta',
                opcaoD: 'San Marino',
                optionD: 'San Marino',
                opcaoE: 'Nauru',
                optionE: 'Nauru',
                respostaCorreta: 'Vaticano',
                correctAnswer: 'Vatican',
                explicacao: 'O Vaticano é um enclave dentro de Roma.',
                explanation: 'The Vatican is an enclave within Rome.',
                materia: 'Geografia',
            },
            {
                pergunta: 'O que é o efeito "El Niño"?',
                question: 'What is the "El Niño" effect?',
                opcaoA: 'Resfriamento das águas do Pacífico',
                optionA: 'Cooling of Pacific waters',
                opcaoB: 'Aquecimento das águas do Pacífico',
                optionB: 'Warming of Pacific waters',
                opcaoC: 'Tornado no Atlântico',
                optionC: 'Tornado in the Atlantic',
                opcaoD: 'Derretimento das calotas polares',
                optionD: 'Polar ice cap melting',
                opcaoE: 'Seca no Saara',
                optionE: 'Drought in the Sahara',
                respostaCorreta: 'Aquecimento das águas do Pacífico',
                correctAnswer: 'Warming of Pacific waters',
                explicacao: 'Altera o clima global periodicamente.',
                explanation: 'It periodically changes the global climate.',
                materia: 'Geografia',
            },

            // --- HISTÓRIA ---
            {
                pergunta: 'Em que ano começou a Segunda Guerra Mundial?',
                question: 'In what year did World War II begin?',
                opcaoA: '1914',
                optionA: '1914',
                opcaoB: '1939',
                optionB: '1939',
                opcaoC: '1945',
                optionC: '1945',
                opcaoD: '1918',
                optionD: '1918',
                opcaoE: '1929',
                optionE: '1929',
                respostaCorreta: '1939',
                correctAnswer: '1939',
                explicacao: 'A guerra começou com a invasão da Polônia em 1939.',
                explanation: 'The war began with the invasion of Poland in 1939.',
                materia: 'História',
            },
            {
                pergunta: 'Quem foi o primeiro presidente do Brasil?',
                question: 'Who was the first president of Brazil?',
                opcaoA: 'Getúlio Vargas',
                optionA: 'Getúlio Vargas',
                opcaoB: 'Deodoro da Fonseca',
                optionB: 'Deodoro da Fonseca',
                opcaoC: 'Dom Pedro II',
                optionC: 'Dom Pedro II',
                opcaoD: 'Juscelino Kubitschek',
                optionD: 'Juscelino Kubitschek',
                opcaoE: 'Tancredo Neves',
                optionE: 'Tancredo Neves',
                respostaCorreta: 'Deodoro da Fonseca',
                correctAnswer: 'Deodoro da Fonseca',
                explicacao: 'Proclamou a República em 1889.',
                explanation: 'Proclaimed the Republic in 1889.',
                materia: 'História',
            },
            {
                pergunta: 'Em que ano ocorreu a Revolução Francesa?',
                question: 'In what year did the French Revolution occur?',
                opcaoA: '1500',
                optionA: '1500',
                opcaoB: '1789',
                optionB: '1789',
                opcaoC: '1822',
                optionC: '1822',
                opcaoD: '1914',
                optionD: '1914',
                opcaoE: '1492',
                optionE: '1492',
                respostaCorreta: '1789',
                correctAnswer: '1789',
                explicacao: 'Marco inicial da Idade Contemporânea.',
                explanation: 'Starting point of the Contemporary Age.',
                materia: 'História',
            },
            {
                pergunta: 'Qual era o nome da política de segregação racial na África do Sul?',
                question: 'What was the name of the racial segregation policy in South Africa?',
                opcaoA: 'Nazismo',
                optionA: 'Nazism',
                opcaoB: 'Holocausto',
                optionB: 'Holocaust',
                opcaoC: 'Apartheid',
                optionC: 'Apartheid',
                opcaoD: 'Fascismo',
                optionD: 'Fascism',
                opcaoE: 'Gulag',
                optionE: 'Gulag',
                respostaCorreta: 'Apartheid',
                correctAnswer: 'Apartheid',
                explicacao: 'Derrubado nos anos 90 com ajuda de Nelson Mandela.',
                explanation: "Overthrown in the 90s with Nelson Mandela's help.",
                materia: 'História',
            },
            {
                pergunta: 'Quem descobriu a América em 1492?',
                question: 'Who discovered America in 1492?',
                opcaoA: 'Pedro Álvares Cabral',
                optionA: 'Pedro Álvares Cabral',
                opcaoB: 'Vasco da Gama',
                optionB: 'Vasco da Gama',
                opcaoC: 'Cristóvão Colombo',
                optionC: 'Christopher Columbus',
                opcaoD: 'Américo Vespúcio',
                optionD: 'Amerigo Vespucci',
                opcaoE: 'Marco Polo',
                optionE: 'Marco Polo',
                respostaCorreta: 'Cristóvão Colombo',
                correctAnswer: 'Christopher Columbus',
                explicacao: 'Chegou às Antilhas financiando pela Espanha.',
                explanation: 'Reached the Antilles funded by Spain.',
                materia: 'História',
            },
            {
                pergunta: 'O que foi a Queda do Muro de Berlim?',
                question: 'What was the Fall of the Berlin Wall?',
                opcaoA: 'Início da 1ª Guerra',
                optionA: 'Beginning of WWI',
                opcaoB: 'Fim da União Soviética',
                optionB: 'End of the Soviet Union',
                opcaoC: 'Símbolo do fim da Guerra Fria (1989)',
                optionC: 'Symbol of the end of the Cold War (1989)',
                opcaoD: 'Uma batalha da 2ª Guerra',
                optionD: 'A WWII battle',
                opcaoE: 'Revolução Industrial',
                optionE: 'Industrial Revolution',
                respostaCorreta: 'Símbolo do fim da Guerra Fria (1989)',
                correctAnswer: 'Symbol of the end of the Cold War (1989)',
                explicacao: 'Reunificou a Alemanha.',
                explanation: 'Reunified Germany.',
                materia: 'História',
            },
            {
                pergunta: 'Qual civilização construiu as pirâmides de Gizé?',
                question: 'Which civilization built the Giza pyramids?',
                opcaoA: 'Gregos',
                optionA: 'Greeks',
                opcaoB: 'Romanos',
                optionB: 'Romans',
                opcaoC: 'Egípcios',
                optionC: 'Egyptians',
                opcaoD: 'Maias',
                optionD: 'Mayans',
                opcaoE: 'Astecas',
                optionE: 'Aztecs',
                respostaCorreta: 'Egípcios',
                correctAnswer: 'Egyptians',
                explicacao: 'Eram túmulos para os faraós.',
                explanation: 'They were tombs for pharaohs.',
                materia: 'História',
            },
            {
                pergunta: 'Quem foi o líder da Revolução Russa de 1917?',
                question: 'Who was the leader of the 1917 Russian Revolution?',
                opcaoA: 'Stalin',
                optionA: 'Stalin',
                opcaoB: 'Lenin',
                optionB: 'Lenin',
                opcaoC: 'Tsar Nicolau II',
                optionC: 'Tsar Nicholas II',
                opcaoD: 'Gorbatchov',
                optionD: 'Gorbachev',
                opcaoE: 'Putin',
                optionE: 'Putin',
                respostaCorreta: 'Lenin',
                correctAnswer: 'Lenin',
                explicacao: 'Liderou os bolcheviques ao poder.',
                explanation: 'Led the Bolsheviks to power.',
                materia: 'História',
            },
            {
                pergunta: 'O que foi o Renascimento?',
                question: 'What was the Renaissance?',
                opcaoA: 'Movimento religioso moderno',
                optionA: 'Modern religious movement',
                opcaoB: 'Renovação cultural e científica (XV-XVI)',
                optionB: 'Cultural and scientific renewal (15th-16th c.)',
                opcaoC: 'Período das trevas',
                optionC: 'Dark Ages',
                opcaoD: 'Independência do Brasil',
                optionD: "Brazil's independence",
                opcaoE: 'Crise de 1929',
                optionE: '1929 Crash',
                respostaCorreta: 'Renovação cultural e científica (XV-XVI)',
                correctAnswer: 'Cultural and scientific renewal (15th-16th c.)',
                explicacao: 'Foco no humanismo e na ciência.',
                explanation: 'Focus on humanism and science.',
                materia: 'História',
            },
            {
                pergunta: 'Quanto tempo durou a Ditadura Militar no Brasil?',
                question: 'How long did the Military Dictatorship in Brazil last?',
                opcaoA: '10 anos',
                optionA: '10 years',
                opcaoB: '21 anos',
                optionB: '21 years',
                opcaoC: '50 anos',
                optionC: '50 years',
                opcaoD: '5 anos',
                optionD: '5 years',
                opcaoE: '30 anos',
                optionE: '30 years',
                respostaCorreta: '21 anos',
                correctAnswer: '21 years',
                explicacao: 'De 1964 até 1985.',
                explanation: 'From 1964 until 1985.',
                materia: 'História',
            },
        ],
    });

    console.log('✅ Seed concluído!');
}

main()
    .catch((e) => {
        console.error('❌ Erro no seed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
